backend:
  name: git-gateway
  branch: master # Branch to update (optional; defaults to master)

  # es para que la pag no se publique mientras trabajamos This line should *not* be indented
  publish_mode: editorial_workflow

  # This line should *not* be indented
  media_folder: "assets/images" # Media files will be stored in the repo under images/uploads

  collections:
    - title: "Servicios" # Used in routes, e.g., /admin/collections/servicios
      label: "Servicios" # Used in the UI
      folder: "content/Servicios" # The path to the folder where the documents are stored
      create: true # Allow users to create new documents in this collection
      slug: "{{year}}-{{month}}-{{day}}-{{slug}}" # Filename template, e.g., YYYY-MM-DD-title.md
      fields: # The fields for each document, usually in front matter
        - { label: "Layout", title: "layout", widget: "hidden", default: "blog" }
        - { label: "Title", title: "title", widget: "string" }
        - { label: "Publish Date", title: "date", widget: "datetime" }
        - { label: "Featured Image", title: "thumbnail", widget: "image" }
        - { label: "Rating (scale of 1-5)", title: "rating", widget: "number" }
        - { label: "Body", title: "body", widget: "markdown" }

    # esto de los fields son los atributos, esta pag https://www.netlifycms.org/docs/widgets/
    # podemos conseguir todos los tipos de atributos en default widgets

